trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-24.04'

variables:
  isMainBranch: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

name: '0.0.$(Rev:r)'

stages:
- stage: buildAndPublish
  displayName: Build and Publish
  jobs:
  - job: 
    steps:
    # clone repo
    - checkout: self
      persistCredentials: true

    # install node/npm
    - task: NodeTool@1
      inputs:
        version: '22.x'

    # Set environment variables and build
    - script: |
        cd packages/amusementconnect
        npm install --include=dev
        NODE_ENV=production INPUT_DIR=src/ OUTPUT_DIR=dist/ npm run build:package
      displayName: "Install and build"

    # auth with amusement connect private registry
    - task: npmAuthenticate@0
      inputs:
        workingFile: $(Build.SourcesDirectory)/packages/amusementconnect/.npmrc

    # publish
    - script: |
        cd packages/amusementconnect
        npm publish
      displayName: "Publish package"