trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-24.04'

variables:
  isMainBranch: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  pnpmConfigCache: $(Pipeline.Workspace)/.pnpm-store

name: '4.4.$(Rev:r)'

stages:
- stage: installDeps
  displayName: Install Dependencies
  jobs:
  - job: 
    steps:
    # clone repo
    - checkout: self
      persistCredentials: true

    # install node/npm
    - task: NodeTool@1
      inputs:
        version: '22.x'

    # auth with amusement connect private registry
    - task: npmAuthenticate@0
      inputs:
        workingFile: $(Build.SourcesDirectory)/.npmrc

    - script: |
        npm install --global corepack@latest
        corepack enable
        corepack prepare pnpm@latest-10 --activate
        pnpm config set store-dir $(pnpm_config_cache)
      displayName: "Setup pnpm"

    - script: |
        pnpm install
        pnpm run build
      displayName: "pnpm install and build"

    - script: |
        pnpm publish --no-git-checks --filter amusementconnect-primevue
      displayName: "pnpm publish"
      
